[phases.setup]
nixPkgs = ['php82', 'php82Extensions.bcmath', 'php82Extensions.ctype', 'php82Extensions.curl', 'php82Extensions.dom', 'php82Extensions.fileinfo', 'php82Extensions.filter', 'php82Extensions.hash', 'php82Extensions.json', 'php82Extensions.mbstring', 'php82Extensions.openssl', 'php82Extensions.pcre', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.session', 'php82Extensions.tokenizer', 'php82Extensions.xml', 'php82Extensions.zip', 'nodejs_18', 'npm']

[phases.install] 
cmds = [
  # Copy environment file
  "cp .env.example .env",
  # Install PHP dependencies
  "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --no-scripts",
  # Generate app key
  "php artisan key:generate --force --no-interaction",
  # Install and build assets
  "npm ci --production",
  "npm run build"
]

[phases.build]
cmds = [
    # Clear any cached config first
    "php artisan config:clear",
    "php artisan route:clear", 
    "php artisan view:clear",
    # Then cache for production
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
